import { BusIndexDataType } from "types/bus";

export const mockBusRoutes: Array<BusIndexDataType> = [
  {
    RouteUID: "TPE10132",
    RouteID: "10132",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "234",
      En: "234",
    },
    DepartureStopNameZh: "板橋",
    DepartureStopNameEn: "Banqiao",
    DestinationStopNameZh: "西門",
    DestinationStopNameEn: "Ximen",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10142",
    RouteID: "10142",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "綠1",
      En: "G1",
    },
    DepartureStopNameZh: "新店",
    DepartureStopNameEn: "Xindian",
    DestinationStopNameZh: "臺北市政府",
    DestinationStopNameEn: "Taipei City Hall",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10181",
    RouteID: "10181",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "205",
      En: "205",
    },
    DepartureStopNameZh: "中華科技大學",
    DepartureStopNameEn: "China University of Science and Tec.",
    DestinationStopNameZh: "東園",
    DestinationStopNameEn: "Dongyuan",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10221",
    RouteID: "10221",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "618",
      En: "618",
    },
    DepartureStopNameZh: "新莊",
    DepartureStopNameEn: "Xinzhuang",
    DestinationStopNameZh: "士林",
    DestinationStopNameEn: "Shilin",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10231",
    RouteID: "10231",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "民權幹線",
      En: "Minquan Metro Bus",
    },
    DepartureStopNameZh: "南港",
    DepartureStopNameEn: "Nangang",
    DestinationStopNameZh: "臺北橋",
    DestinationStopNameEn: "Taipei Bridge",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10232",
    RouteID: "10232",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "紅25",
      En: "R25",
    },
    DepartureStopNameZh: "南港",
    DepartureStopNameEn: "Nangang",
    DestinationStopNameZh: "捷運北門站",
    DestinationStopNameEn: "MRT Beimen Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10241",
    RouteID: "10241",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "藍36",
      En: "BL36",
    },
    DepartureStopNameZh: "汐止社后",
    DepartureStopNameEn: "Xizhi Shehou",
    DestinationStopNameZh: "捷運昆陽站",
    DestinationStopNameEn: "MRT Kunyang Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10251",
    RouteID: "10251",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "南京幹線",
      En: "Nanjing Metro Bus",
    },
    DepartureStopNameZh: "南港高工",
    DepartureStopNameEn: "Nangang Vocational High School",
    DestinationStopNameZh: "圓環",
    DestinationStopNameEn: "Taipei Circle",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10253",
    RouteID: "10253",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "21",
      En: "21",
    },
    DepartureStopNameZh: "捷運圓山站",
    DepartureStopNameEn: "MRT Yuanshan Sta.",
    DestinationStopNameZh: "捷運文德站",
    DestinationStopNameEn: "MRT Wende Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10261",
    RouteID: "10261",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "紅33",
      En: "R33",
    },
    DepartureStopNameZh: "葫蘆里",
    DepartureStopNameEn: "Hulu Li",
    DestinationStopNameZh: "聯合醫院中興院區(西寧)",
    DestinationStopNameEn: "Tpe Hospital Zhongxin Branch(Xining)",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10262",
    RouteID: "10262",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "2",
      En: "2",
    },
    DepartureStopNameZh: "台北海大",
    DepartureStopNameEn: "Taipei University of Maritime Technology",
    DestinationStopNameZh: "臺大醫院",
    DestinationStopNameEn: "NTU Hospital",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10263",
    RouteID: "10263",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "536",
      En: "536",
    },
    DepartureStopNameZh: "台北海大",
    DepartureStopNameEn: "Taipei University of Maritime Technology",
    DestinationStopNameZh: "大同之家",
    DestinationStopNameEn: "Datung House",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10272",
    RouteID: "10272",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "303",
      En: "303",
    },
    DepartureStopNameZh: "捷運劍潭站",
    DepartureStopNameEn: "MRT Jiantan Sta.",
    DestinationStopNameZh: "大坪尾",
    DestinationStopNameEn: "Dapingwei",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10273",
    RouteID: "10273",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "303區",
      En: "303Shuttle",
    },
    DepartureStopNameZh: "捷運劍潭站",
    DepartureStopNameEn: "MRT Jiantan Sta.",
    DestinationStopNameZh: "平等里",
    DestinationStopNameEn: "Pingdeng Li",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10277",
    RouteID: "10277",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "542",
      En: "542",
    },
    DepartureStopNameZh: "捷運圓山站",
    DepartureStopNameEn: "MRT Yuanshan Sta.",
    DestinationStopNameZh: "捷運中山國中站",
    DestinationStopNameEn: "MRT ZhongShan Junior High Sch. Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10278",
    RouteID: "10278",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "669",
      En: "669",
    },
    DepartureStopNameZh: "三重",
    DepartureStopNameEn: "Sanchong",
    DestinationStopNameZh: "市政府",
    DestinationStopNameEn: "Taipei City Hall",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10282",
    RouteID: "10282",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "663",
      En: "663",
    },
    DepartureStopNameZh: "新莊",
    DepartureStopNameEn: "Xinzhuang",
    DestinationStopNameZh: "國父紀念館",
    DestinationStopNameEn: "National Dr. SYS Memorial Hall",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10283",
    RouteID: "10283",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "235",
      En: "235",
    },
    DepartureStopNameZh: "新莊",
    DepartureStopNameEn: "Xinzhuang",
    DestinationStopNameZh: "國父紀念館",
    DestinationStopNameEn: "Dr. Sun Yat-sen Memorial Hall",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10291",
    RouteID: "10291",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "棕1",
      En: "BR1",
    },
    DepartureStopNameZh: "松山車站",
    DepartureStopNameEn: "Songshan Station",
    DestinationStopNameZh: "松山機場",
    DestinationStopNameEn: "Taipei Songshan Airport",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10292",
    RouteID: "10292",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "藍10",
      En: "BL10",
    },
    DepartureStopNameZh: "民生社區",
    DepartureStopNameEn: "Mingsheng Community",
    DestinationStopNameZh: "南港花園社區",
    DestinationStopNameEn: "Nangang Garden Community",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10293",
    RouteID: "10293",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "民生幹線",
      En: "Minsheng Metro Bus",
    },
    DepartureStopNameZh: "麥帥新城",
    DepartureStopNameEn: "MacArthur New Village",
    DestinationStopNameZh: "圓環",
    DestinationStopNameEn: "Taipei Circle",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10326",
    RouteID: "10326",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "648",
      En: "648",
    },
    DepartureStopNameZh: "錦繡山莊",
    DepartureStopNameEn: "Jinxiu Moubtaion Villa",
    DestinationStopNameZh: "臺北車站",
    DestinationStopNameEn: "Taipei Main Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10328",
    RouteID: "10328",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "643",
      En: "643",
    },
    DepartureStopNameZh: "錦繡山莊",
    DepartureStopNameEn: "Jinxiu Moubtaion Villa",
    DestinationStopNameZh: "復興北村",
    DestinationStopNameEn: "Fuxing Bei Village",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10331",
    RouteID: "10331",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "647",
      En: "647",
    },
    DepartureStopNameZh: "大崎腳",
    DepartureStopNameEn: "Daqijiao",
    DestinationStopNameZh: "捷運市政府站",
    DestinationStopNameEn: "MRT Taipei City Hall Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10332",
    RouteID: "10332",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "松江新生幹線",
      En: "Songjiang Xinsheng Metro Bus",
    },
    DepartureStopNameZh: "青潭",
    DepartureStopNameEn: "Qingtan",
    DestinationStopNameZh: "復興北村",
    DestinationStopNameEn: "Fuxing Bei Village",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10333",
    RouteID: "10333",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "644",
      En: "644",
    },
    DepartureStopNameZh: "青潭",
    DepartureStopNameEn: "Qingtan",
    DestinationStopNameZh: "博愛路",
    DestinationStopNameEn: "Boai Rd.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10334",
    RouteID: "10334",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "基隆路幹線",
      En: "Keelung Rd. Metro Bus",
    },
    DepartureStopNameZh: "大崎腳",
    DepartureStopNameEn: "Daqijiao",
    DestinationStopNameZh: "捷運市政府站",
    DestinationStopNameEn: "MRT Taipei City Hall Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10414",
    RouteID: "10414",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "261",
      En: "261",
    },
    DepartureStopNameZh: "蘆洲",
    DepartureStopNameEn: "Luzhou",
    DestinationStopNameZh: "臺大醫院",
    DestinationStopNameEn: "NTU Hospital",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10415",
    RouteID: "10415",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "221",
      En: "221",
    },
    DepartureStopNameZh: "蘆洲",
    DepartureStopNameEn: "Luzhou",
    DestinationStopNameZh: "臺北車站",
    DestinationStopNameEn: "Taipei Main Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
  {
    RouteUID: "TPE10416",
    RouteID: "10416",
    HasSubRoutes: true,
    BusRouteType: 11,
    RouteName: {
      Zh_tw: "232",
      En: "232",
    },
    DepartureStopNameZh: "蘆洲",
    DepartureStopNameEn: "Luzhou",
    DestinationStopNameZh: "捷運善導寺站",
    DestinationStopNameEn: "MRT Shandao Temple Sta.",
    City: "Taipei",
    CityCode: "TPE",
    UpdateTime: "2021-11-26T18:33:53+08:00",
    VersionID: 1336,
  },
];
